FROM golang:1.22-bookworm AS minimum

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go test ./...

FROM golang:1.27.1-bookworm AS verify

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go test -race ./...
RUN CGO_ENABLED=0 go vet ./...
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm go build ./...
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build ./...
RUN CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build ./...
RUN CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build ./...
RUN CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build ./...
RUN CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build ./...
